# Generated by Django 3.2.6 on 2021-11-26 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0002_auto_20211126_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='storehouse.user'),
            preserve_default=False,
        ),
    ]
