# Generated by Django 3.2.6 on 2021-11-27 19:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0003_product_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryAdmin',
        ),
        migrations.DeleteModel(
            name='ProductAdmin',
        ),
        migrations.DeleteModel(
            name='UserAdmin',
        ),
        migrations.AddField(
            model_name='product',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
