# Generated by Django 3.2.6 on 2021-11-27 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0004_auto_20211127_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
