# Generated by Django 3.2.6 on 2021-11-27 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0005_product_update_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='update_time',
            new_name='update_date',
        ),
    ]
